Rf:
    type: entity
    table: RF
    indexes:
        fk_RF_Personal1_idx:
            columns:
                - Personal_Email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        texto:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: Texto
        keywords:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: Keywords
    manyToOne:
        personalEmail:
            targetEntity: Personal
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Personal_Email:
                    referencedColumnName: Email
            orphanRemoval: false
    lifecycleCallbacks: {  }
