Tem치tica:
    type: entity
    table: Tem치tica
    indexes:
        fk_Tem치tica_Personal1_idx:
            columns:
                - Personal_Email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        enunciado:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: Enunciado
        tematica:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: Tematica
    manyToOne:
        personalEmail:
            targetEntity: Personal
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Personal_Email:
                    referencedColumnName: Email
            orphanRemoval: false
    manyToMany:
        grupoSoporte:
            targetEntity: GrupoSoporte
            cascade: {  }
            fetch: LAZY
            mappedBy: tem치tica
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
